### ISSUE TITLE
Model out 7.62 Ammunition

### ISSUE THREAD

**Issue by rovangju** [SkullKid2113/GameModel#5]
Now that we've made our ammunition base class in #3 , let's make implementations of the bullet types:

- Make a class (762Ammo) that extends Ammunition
- Set the properties (weight, damage, friction, damage per, ammotype)  using the super() function in the constructor of the 762Ammo class

**Comment by SkullKid2113** [comment]
Yes?

**Comment by rovangju** [comment]
es gut
