### ISSUE TITLE
Implement "equipWeapon" method in the Player class

### ISSUE THREAD

**Issue by rovangju** [SkullKid2113/GameModel#8]
I've implemented a test suite to ensure the functionality is behaving as expected, also created the method stub (equipWeapon) in the class so I could write tests against it, and you could fill it in.

Requirements:

- Pass a weapon object in, and it goes into the weaponSlots array in the player object 
- No duplicate weapons can be added. In our game, you can't triple stamp a double stamp, so no carrying 2 AK 47's.

**Comment by SkullKid2113** [comment]
This passed the test parameters

**Comment by rovangju** [comment]
FTFY. 
Take a look at Discord link :)
